name: first workflow

on:
  workflow_dispatch

jobs:
  firstjob:
    runs-on: ubuntu-latest
    steps:
        - name: firstJob script
          shell: bash
          run:  echo Hello World! This is the first job
        - name: checkout the repository
          uses: actions/checkout@v3
        - name: greetings
          id: greetings
          uses: actions/hello-world-javascript-action@main
          with:
           who-to-greet: 'Rohan'
        - name: time
          run: |
            echo "The time of the greeting was at: ${{steps.greeting.output.time}}"

  secondJob:
    runs-on: ubuntu-latest
    steps:
        - name: secondJob script
          run: |
            echo this is the second job
            echo and this is a multi-line script
